from __future__ import annotations

import asyncio
import json

from app.db import init_db, get_db

CATEGORIES = [
    {
        "id": "ET-01",
        "name": "口算速算",
        "code": "mental",
        "description": "心算快速计算，培养数感和运算直觉",
        "sort_order": 1,
        "subtypes": [
            {
                "id": "ET-0101",
                "name": "整数口算——一位数加减",
                "code": "mental_int_add_sub_1d",
                "difficulty_range": ["A"],
                "related_error_codes": ["E01"],
                "knowledge_points": ["20以内加减法", "100以内加减法"],
                "description": "一位数加减法口算，如 8+7, 15-9",
                "example_problem": "8+7=",
                "example_answer": "15",
                "grade_range": [1, 2, 3, 4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0102",
                "name": "整数口算——两位数加减",
                "code": "mental_int_add_sub_2d",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E01", "E02", "E03"],
                "knowledge_points": ["两位数加减法", "凑十法"],
                "description": "两位数加减法口算，如 47+28, 82-35",
                "example_problem": "47+28=",
                "example_answer": "75",
                "grade_range": [2, 3, 4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0103",
                "name": "整数口算——乘除法",
                "code": "mental_int_mul_div",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E01", "E06"],
                "knowledge_points": ["九九乘法表", "表内除法"],
                "description": "一位数乘除法及特殊速算，如 25×4, 360÷9",
                "example_problem": "25×4=",
                "example_answer": "100",
                "grade_range": [3, 4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0104",
                "name": "小数口算",
                "code": "mental_decimal",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E06", "E09"],
                "knowledge_points": ["小数加减法", "小数乘除法"],
                "description": "小数四则口算，如 0.5+0.3, 2.4÷0.6",
                "example_problem": "0.5+0.3=",
                "example_answer": "0.8",
                "grade_range": [4, 5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0105",
                "name": "分数口算",
                "code": "mental_fraction",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E01", "E02", "E06"],
                "knowledge_points": ["分数加减法", "分数乘除法"],
                "description": "分数基本运算口算，如 1/2+1/3, 3/4×4",
                "example_problem": "1/2+1/3=",
                "example_answer": "5/6",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0106",
                "name": "百分数口算",
                "code": "mental_percent",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E05", "E06"],
                "knowledge_points": ["百分数意义", "百分数与分数小数互化"],
                "description": "百分数计算口算，如 25%×80, 15%×200",
                "example_problem": "25%×80=",
                "example_answer": "20",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0107",
                "name": "混合口算",
                "code": "mental_mixed",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E05", "E06", "E09"],
                "knowledge_points": ["分数小数百分数混合", "速算技巧"],
                "description": "交叉类型快速心算，含分数、小数、百分数",
                "example_problem": "3/4×0.8=",
                "example_answer": "0.6",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0108",
                "name": "整数口算——乘除混合",
                "code": "mental_int_mul_div_chain",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E01", "E05"],
                "knowledge_points": ["乘除混合速算", "运算顺序"],
                "description": "整数乘除混合口算，如 72÷9×5",
                "example_problem": "72÷9×5=",
                "example_answer": "40",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0109",
                "name": "特殊数口算",
                "code": "mental_special_nums",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E01", "E10"],
                "knowledge_points": ["特殊数速算", "平方数", "立方数"],
                "description": "平方数、立方数、特殊积口算，如 11×11, 15²",
                "example_problem": "15²=",
                "example_answer": "225",
                "grade_range": [5, 6],
                "textbook_unit": "通用",
            },
        ],
    },
    {
        "id": "ET-02",
        "name": "竖式计算",
        "code": "vertical",
        "description": "列竖式进行多位数四则运算，训练计算规范",
        "sort_order": 2,
        "subtypes": [
            {
                "id": "ET-0201",
                "name": "多位数加减法竖式",
                "code": "vertical_add_sub",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E01", "E02", "E03", "E04"],
                "knowledge_points": ["进位加法", "退位减法", "数位对齐"],
                "description": "多位数加减法竖式，如 402-178, 567+289",
                "example_problem": "402-178=",
                "example_answer": "224",
                "grade_range": [3, 4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0202",
                "name": "两位数乘两位数竖式",
                "code": "vertical_mul_2x2",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E02", "E04", "E08"],
                "knowledge_points": ["两位数乘法", "部分积对齐"],
                "description": "两位数×两位数竖式，如 23×45",
                "example_problem": "23×45=",
                "example_answer": "1035",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0203",
                "name": "三位数乘两位数竖式",
                "code": "vertical_mul_3x2",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E02", "E04", "E08"],
                "knowledge_points": ["多位数乘法", "连续进位"],
                "description": "三位数×两位数竖式，如 312×25",
                "example_problem": "312×25=",
                "example_answer": "7800",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0204",
                "name": "多位数除法竖式",
                "code": "vertical_div",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E01", "E03", "E04"],
                "knowledge_points": ["除法竖式", "试商调商", "余数处理"],
                "description": "三位数÷两位数竖式，如 936÷24",
                "example_problem": "936÷24=",
                "example_answer": "39",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0205",
                "name": "小数加减竖式",
                "code": "vertical_dec_add_sub",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E04", "E06"],
                "knowledge_points": ["小数点对齐", "小数加减法"],
                "description": "小数加减法竖式，如 3.14+2.86",
                "example_problem": "3.14+2.86=",
                "example_answer": "6",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0206",
                "name": "小数乘除竖式",
                "code": "vertical_dec_mul_div",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E04", "E06", "E08"],
                "knowledge_points": ["小数乘法", "小数除法", "小数点定位"],
                "description": "小数×整数、小数×小数竖式，如 3.14×2.5",
                "example_problem": "3.14×2.5=",
                "example_answer": "7.85",
                "grade_range": [5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0207",
                "name": "连加连减竖式",
                "code": "vertical_chain_add_sub",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E02", "E03", "E08"],
                "knowledge_points": ["连加连减", "竖式竖排"],
                "description": "三个及以上数的连加或连减竖式",
                "example_problem": "367+258+149=",
                "example_answer": "774",
                "grade_range": [3, 4, 5, 6],
                "textbook_unit": "通用",
            },
        ],
    },
    {
        "id": "ET-03",
        "name": "脱式计算",
        "code": "step_by_step",
        "description": "递等式/分步计算，训练运算顺序和多步计算能力",
        "sort_order": 3,
        "subtypes": [
            {
                "id": "ET-0301",
                "name": "整数四则脱式（无括号）",
                "code": "step_int_no_paren",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E05", "E08"],
                "knowledge_points": ["运算顺序", "先乘除后加减"],
                "description": "整数四则混合运算（无括号），如 36+24÷6",
                "example_problem": "36+24÷6=",
                "example_answer": "40",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0302",
                "name": "整数四则脱式（有括号）",
                "code": "step_int_paren",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E05", "E08"],
                "knowledge_points": ["括号改变运算顺序", "先算括号内"],
                "description": "含括号的整数四则混合运算，如 (36+24)÷6",
                "example_problem": "(36+24)÷6=",
                "example_answer": "10",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0303",
                "name": "小数四则脱式",
                "code": "step_decimal",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E05", "E06", "E08"],
                "knowledge_points": ["小数四则混合运算", "运算顺序"],
                "description": "小数四则混合运算脱式，如 3.6×2.5+4.8÷1.2",
                "example_problem": "3.6×2.5+4.8÷1.2=",
                "example_answer": "13",
                "grade_range": [5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0304",
                "name": "分数四则脱式",
                "code": "step_fraction",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E01", "E03", "E05", "E08"],
                "knowledge_points": ["分数四则混合运算", "运算顺序"],
                "description": "分数四则混合运算脱式，如 2/3+5/6×3/5",
                "example_problem": "2/3+5/6×3/5=",
                "example_answer": "7/6",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0305",
                "name": "混合运算脱式",
                "code": "step_mixed",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E05", "E06", "E09"],
                "knowledge_points": ["分数小数百分数混合运算", "运算顺序"],
                "description": "分数+小数+百分数混合脱式计算",
                "example_problem": "3/4×0.8+1/2=",
                "example_answer": "1.1",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
        ],
    },
    {
        "id": "ET-04",
        "name": "简便运算",
        "code": "shortcut",
        "description": "运用运算律和巧算技巧进行简便计算",
        "sort_order": 4,
        "subtypes": [
            {
                "id": "ET-0401",
                "name": "乘法交换律",
                "code": "shortcut_commute",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E10"],
                "knowledge_points": ["乘法交换律 a×b=b×a"],
                "description": "利用乘法交换律调整运算顺序",
                "example_problem": "25×7×4=",
                "example_answer": "700",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0402",
                "name": "乘法结合律",
                "code": "shortcut_assoc",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E10"],
                "knowledge_points": ["乘法结合律 (a×b)×c=a×(b×c)"],
                "description": "利用乘法结合律凑整",
                "example_problem": "8×125×7=",
                "example_answer": "7000",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0403",
                "name": "乘法分配律",
                "code": "shortcut_distrib",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E10"],
                "knowledge_points": ["乘法分配律 (a+b)×c=a×c+b×c"],
                "description": "正用与逆用乘法分配律",
                "example_problem": "25×(40+4)=",
                "example_answer": "1100",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0404",
                "name": "减法性质",
                "code": "shortcut_sub_prop",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E10"],
                "knowledge_points": ["减法性质 a-b-c=a-(b+c)"],
                "description": "利用减法运算性质简便计算",
                "example_problem": "536-143-57=",
                "example_answer": "336",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0405",
                "name": "除法性质",
                "code": "shortcut_div_prop",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E10"],
                "knowledge_points": ["除法性质 a÷b÷c=a÷(b×c)"],
                "description": "利用除法运算性质简便计算",
                "example_problem": "3600÷25÷4=",
                "example_answer": "36",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0406",
                "name": "凑整巧算",
                "code": "shortcut_round",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E10"],
                "knowledge_points": ["凑整法", "125×8=1000", "25×4=100"],
                "description": "利用125×8、25×4等凑整进行巧算",
                "example_problem": "125×32=",
                "example_answer": "4000",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0407",
                "name": "拆项巧算",
                "code": "shortcut_decompose",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E10"],
                "knowledge_points": ["拆项法", "99×37+37=100×37"],
                "description": "利用拆项法进行简便运算",
                "example_problem": "99×37+37=",
                "example_answer": "3700",
                "grade_range": [5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0408",
                "name": "分数简便运算",
                "code": "shortcut_fraction",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E10"],
                "knowledge_points": ["分数运算律", "分数分配律应用"],
                "description": "在分数运算中运用运算律",
                "example_problem": "7/12×5+7/12×7=",
                "example_answer": "7",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0409",
                "name": "加减法凑整",
                "code": "shortcut_add_round",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E10"],
                "knowledge_points": ["凑整法（加减）", "找补数"],
                "description": "加减法中凑整简便计算，如 998+376=1000+376-2",
                "example_problem": "998+376=",
                "example_answer": "1374",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0410",
                "name": "小数简便运算",
                "code": "shortcut_decimal",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E10"],
                "knowledge_points": ["小数运算律", "小数分配律"],
                "description": "在小数运算中运用运算律",
                "example_problem": "2.5×3.6+2.5×6.4=",
                "example_answer": "25",
                "grade_range": [5, 6],
                "textbook_unit": "通用",
            },
        ],
    },
    {
        "id": "ET-05",
        "name": "列式计算",
        "code": "word_expression",
        "description": "将文字描述转化为数学表达式并计算",
        "sort_order": 5,
        "subtypes": [
            {
                "id": "ET-0501",
                "name": "整数文字题",
                "code": "word_int",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E05", "E10"],
                "knowledge_points": ["文字题转化", "运算关系理解"],
                "description": "整数运算文字题，如\"25的4倍与36的差\"",
                "example_problem": "25的4倍与36的差是多少？",
                "example_answer": "64",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0502",
                "name": "分数文字题",
                "code": "word_frac",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E01", "E05"],
                "knowledge_points": ["分数文字题", "分数乘除意义"],
                "description": "分数运算文字题，如\"2/3的3/5是多少\"",
                "example_problem": "2/3的3/5是多少？",
                "example_answer": "2/5",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0503",
                "name": "百分数文字题",
                "code": "word_pct",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E05", "E06"],
                "knowledge_points": ["百分数应用", "百分数文字题"],
                "description": "百分数运算文字题，如\"80的25%是多少\"",
                "example_problem": "80的25%是多少？",
                "example_answer": "20",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0504",
                "name": "比的文字题",
                "code": "word_ratio",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E04", "E05"],
                "knowledge_points": ["比的意义", "按比分配"],
                "description": "比相关文字题，如\"甲乙之比3:5,甲是60,乙是?\"",
                "example_problem": "甲乙之比是3:5，甲是60，乙是多少？",
                "example_answer": "100",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0505",
                "name": "综合文字题",
                "code": "word_comprehensive",
                "difficulty_range": ["C"],
                "related_error_codes": ["E05", "E08"],
                "knowledge_points": ["多步推理", "综合列式"],
                "description": "需要多步推理的综合文字题",
                "example_problem": "一个数的3/5比它的1/2多6，这个数是多少？",
                "example_answer": "60",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
        ],
    },
    {
        "id": "ET-06",
        "name": "图形计算",
        "code": "geometry",
        "description": "圆、圆柱、圆锥等图形的周长、面积、体积计算",
        "sort_order": 6,
        "subtypes": [
            {
                "id": "ET-0601",
                "name": "圆的周长",
                "code": "geo_circle_perimeter",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E07"],
                "knowledge_points": ["圆周长公式 C=2πr=πd"],
                "description": "已知半径或直径求圆的周长",
                "example_problem": "半径5cm的圆的周长",
                "example_answer": "10π cm",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0602",
                "name": "圆的面积",
                "code": "geo_circle_area",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E07"],
                "knowledge_points": ["圆面积公式 S=πr²"],
                "description": "已知半径或直径求圆的面积",
                "example_problem": "直径10cm的圆的面积",
                "example_answer": "25π cm²",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0603",
                "name": "圆环面积",
                "code": "geo_annulus",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E07"],
                "knowledge_points": ["圆环面积 S=π(R²-r²)"],
                "description": "已知外圆和内圆半径求环形面积",
                "example_problem": "外圆半径5cm、内圆半径3cm的环形面积",
                "example_answer": "16π cm²",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0604",
                "name": "扇形面积",
                "code": "geo_sector",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E07"],
                "knowledge_points": ["扇形面积 S=n/360×πr²"],
                "description": "已知半径和圆心角求扇形面积",
                "example_problem": "半径6cm、圆心角120°的扇形面积",
                "example_answer": "12π cm²",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0605",
                "name": "组合图形面积",
                "code": "geo_composite",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E07", "E08"],
                "knowledge_points": ["组合图形", "割补法"],
                "description": "矩形+半圆、L形等组合图形面积",
                "example_problem": "一个长8cm、宽4cm的矩形，一端加一个直径4cm的半圆，总面积",
                "example_answer": "(32+2π) cm²",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0606",
                "name": "不规则图形面积估算",
                "code": "geo_irregular",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E07", "E11"],
                "knowledge_points": ["方格法估算", "不规则图形"],
                "description": "用方格法或割补法估算不规则图形面积",
                "example_problem": "用方格法估算一片树叶的面积（每格1cm²）",
                "example_answer": "估算值",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0607",
                "name": "长方体/正方体表面积",
                "code": "geo_box_surface",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E07"],
                "knowledge_points": ["长方体表面积", "正方体表面积"],
                "description": "长方体或正方体的表面积计算",
                "example_problem": "长5cm、宽4cm、高3cm的长方体表面积",
                "example_answer": "94 cm²",
                "grade_range": [5, 6],
                "textbook_unit": "六年级下册",
            },
            {
                "id": "ET-0608",
                "name": "长方体/正方体体积",
                "code": "geo_box_volume",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E07"],
                "knowledge_points": ["长方体体积 V=abh", "正方体体积 V=a³"],
                "description": "长方体或正方体的体积计算",
                "example_problem": "棱长为4cm的正方体体积",
                "example_answer": "64 cm³",
                "grade_range": [5, 6],
                "textbook_unit": "六年级下册",
            },
            {
                "id": "ET-0609",
                "name": "圆柱表面积",
                "code": "geo_cylinder_surface",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E07"],
                "knowledge_points": ["圆柱侧面积", "圆柱表面积"],
                "description": "圆柱的侧面积和表面积计算",
                "example_problem": "底面半径3cm、高10cm的圆柱表面积",
                "example_answer": "(60π+18π) cm²",
                "grade_range": [6],
                "textbook_unit": "六年级下册",
            },
            {
                "id": "ET-0610",
                "name": "圆柱体积",
                "code": "geo_cylinder_volume",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E07"],
                "knowledge_points": ["圆柱体积 V=πr²h"],
                "description": "圆柱的体积计算",
                "example_problem": "底面半径4cm、高12cm的圆柱体积",
                "example_answer": "192π cm³",
                "grade_range": [6],
                "textbook_unit": "六年级下册",
            },
            {
                "id": "ET-0611",
                "name": "圆锥体积",
                "code": "geo_cone_volume",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E07"],
                "knowledge_points": ["圆锥体积 V=1/3πr²h"],
                "description": "圆锥的体积计算",
                "example_problem": "底面半径3cm、高12cm的圆锥体积",
                "example_answer": "36π cm³",
                "grade_range": [6],
                "textbook_unit": "六年级下册",
            },
        ],
    },
    {
        "id": "ET-07",
        "name": "分数运算",
        "code": "fraction_ops",
        "description": "分数加减乘除及与百分数小数互化",
        "sort_order": 7,
        "subtypes": [
            {
                "id": "ET-0701",
                "name": "分数加减——同分母",
                "code": "frac_add_sub_same",
                "difficulty_range": ["A"],
                "related_error_codes": ["E01", "E06"],
                "knowledge_points": ["同分母分数加减", "分数单位"],
                "description": "同分母分数加减法",
                "example_problem": "3/7+2/7=",
                "example_answer": "5/7",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0702",
                "name": "分数加减——异分母",
                "code": "frac_add_sub_diff",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E01", "E06"],
                "knowledge_points": ["异分母通分", "异分母加减"],
                "description": "异分母分数加减法（需通分）",
                "example_problem": "2/3+1/4=",
                "example_answer": "11/12",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0703",
                "name": "分数乘法",
                "code": "frac_mul",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E01"],
                "knowledge_points": ["分数×整数", "分数×分数"],
                "description": "分数乘整数、分数乘分数",
                "example_problem": "2/3×3/4=",
                "example_answer": "1/2",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0704",
                "name": "分数除法",
                "code": "frac_div",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E02"],
                "knowledge_points": ["分数÷整数", "分数÷分数", "颠倒相乘"],
                "description": "分数除法（颠倒相乘法）",
                "example_problem": "3/5÷3/4=",
                "example_answer": "4/5",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0705",
                "name": "分数四则混合",
                "code": "frac_mixed_ops",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E03", "E05"],
                "knowledge_points": ["分数四则混合运算", "运算顺序"],
                "description": "分数加减乘除混合运算",
                "example_problem": "2/3÷1/2+3/4×4/5=",
                "example_answer": "7/5",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0706",
                "name": "分数与小数互化",
                "code": "frac_dec_convert",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E06", "E09"],
                "knowledge_points": ["分数化小数", "小数化分数", "有限小数判定"],
                "description": "分数和小数的相互转化",
                "example_problem": "把3/8化成小数",
                "example_answer": "0.375",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0707",
                "name": "分数与百分数互化",
                "code": "frac_pct_convert",
                "difficulty_range": ["A", "B", "C"],
                "related_error_codes": ["E05", "E06"],
                "knowledge_points": ["分数化百分数", "百分数化分数"],
                "description": "分数和百分数的相互转化",
                "example_problem": "把3/4化成百分数",
                "example_answer": "75%",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0708",
                "name": "繁分数化简",
                "code": "frac_complex_simplify",
                "difficulty_range": ["C"],
                "related_error_codes": ["E03", "E05"],
                "knowledge_points": ["繁分数", "化简"],
                "description": "繁分数化简为最简分数",
                "example_problem": "化简 (1/2+1/3)/(1/2-1/3)=",
                "example_answer": "5",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0709",
                "name": "带分数加减",
                "code": "frac_mixed_add_sub",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E01", "E03"],
                "knowledge_points": ["带分数加减", "整数部分和分数部分分别运算"],
                "description": "带分数加减运算",
                "example_problem": "2又1/3+1又1/2=",
                "example_answer": "3又5/6",
                "grade_range": [5, 6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0710",
                "name": "分数连乘",
                "code": "frac_chain_mul",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E01", "E03"],
                "knowledge_points": ["分数连乘", "先约分再计算"],
                "description": "三个及以上分数的连乘运算",
                "example_problem": "2/3×3/4×4/5=",
                "example_answer": "2/5",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0711",
                "name": "分数连除",
                "code": "frac_chain_div",
                "difficulty_range": ["C"],
                "related_error_codes": ["E02", "E05"],
                "knowledge_points": ["分数连除", "除号变乘号翻转"],
                "description": "三个及以上分数的连除运算",
                "example_problem": "4/5÷2/3÷1/2=",
                "example_answer": "12/5",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0712",
                "name": "比与分数综合",
                "code": "frac_ratio_compound",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E04", "E05"],
                "knowledge_points": ["比化分数", "分数化比", "比和分数关系"],
                "description": "比与分数的综合运算",
                "example_problem": "把3:5化成最简分数",
                "example_answer": "3/5",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
        ],
    },
    {
        "id": "ET-08",
        "name": "单位换算与估算",
        "code": "unit_estimation",
        "description": "计量单位换算和计算结果估算",
        "sort_order": 8,
        "subtypes": [
            {
                "id": "ET-0801",
                "name": "长度单位换算",
                "code": "unit_length",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E06"],
                "knowledge_points": ["km/m/dm/cm/mm", "长度单位进率"],
                "description": "千米、米、分米、厘米、毫米之间的换算",
                "example_problem": "3.5km=?m",
                "example_answer": "3500m",
                "grade_range": [3, 4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0802",
                "name": "面积单位换算",
                "code": "unit_area",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E06"],
                "knowledge_points": ["m²/dm²/cm²", "面积单位进率"],
                "description": "平方米、平方分米、平方厘米等面积单位换算",
                "example_problem": "3.6m²=?dm²",
                "example_answer": "360dm²",
                "grade_range": [4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0803",
                "name": "体积单位换算",
                "code": "unit_volume",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E06"],
                "knowledge_points": ["m³/dm³/cm³/L/mL", "体积单位进率"],
                "description": "立方米、立方分米、立方厘米、升、毫升等体积单位换算",
                "example_problem": "2.5L=?mL",
                "example_answer": "2500mL",
                "grade_range": [5, 6],
                "textbook_unit": "六年级下册",
            },
            {
                "id": "ET-0804",
                "name": "质量单位换算",
                "code": "unit_mass",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E06"],
                "knowledge_points": ["t/kg/g", "质量单位进率"],
                "description": "吨、千克、克之间的换算",
                "example_problem": "2.4t=?kg",
                "example_answer": "2400kg",
                "grade_range": [3, 4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0805",
                "name": "时间单位换算",
                "code": "unit_time",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E06"],
                "knowledge_points": ["时/分/秒", "时间单位进率"],
                "description": "时、分、秒之间的换算",
                "example_problem": "2.5小时=?分钟",
                "example_answer": "150分钟",
                "grade_range": [3, 4, 5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0806",
                "name": "计算估算",
                "code": "unit_estimate",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E11"],
                "knowledge_points": ["估算策略", "结果范围判断"],
                "description": "估算计算结果的范围或近似值",
                "example_problem": "估算 3.14×8.9 的结果大约是多少",
                "example_answer": "约28",
                "grade_range": [5, 6],
                "textbook_unit": "通用",
            },
            {
                "id": "ET-0807",
                "name": "综合单位换算",
                "code": "unit_comprehensive",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E06", "E07"],
                "knowledge_points": ["多步单位换算", "复合单位"],
                "description": "涉及面积→体积、长度→面积等多步单位换算",
                "example_problem": "一个长5m、宽4m的房间，铺边长50cm的方砖，需要多少块？",
                "example_answer": "80块",
                "grade_range": [5, 6],
                "textbook_unit": "六年级下册",
            },
        ],
    },
    {
        "id": "ET-09",
        "name": "比与比例计算",
        "code": "ratio_proportion",
        "description": "比、比例、正反比例相关计算",
        "sort_order": 9,
        "subtypes": [
            {
                "id": "ET-0901",
                "name": "化简比",
                "code": "ratio_simplify",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E04"],
                "knowledge_points": ["化简整数比", "化简分数比", "最大公因数"],
                "description": "化简整数比和分数比",
                "example_problem": "化简比 24:36",
                "example_answer": "2:3",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0902",
                "name": "求比值",
                "code": "ratio_value",
                "difficulty_range": ["A", "B"],
                "related_error_codes": ["E04"],
                "knowledge_points": ["比值=前项÷后项", "分数表示比值"],
                "description": "求比的比值（前项÷后项）",
                "example_problem": "求比值 15:25",
                "example_answer": "3/5",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0903",
                "name": "按比分配",
                "code": "ratio_distribute",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E04", "E05"],
                "knowledge_points": ["按比分配", "总份数法"],
                "description": "将总量按给定的比进行分配",
                "example_problem": "把120按2:3分配",
                "example_answer": "48和72",
                "grade_range": [6],
                "textbook_unit": "六年级上册",
            },
            {
                "id": "ET-0904",
                "name": "比例尺计算",
                "code": "ratio_scale",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E04", "E06"],
                "knowledge_points": ["比例尺", "图上距离与实际距离"],
                "description": "根据比例尺进行图上距离和实际距离的换算",
                "example_problem": "比例尺1:50000，图上3cm，实际距离多少km？",
                "example_answer": "1.5km",
                "grade_range": [6],
                "textbook_unit": "六年级下册",
            },
            {
                "id": "ET-0905",
                "name": "正比例应用",
                "code": "ratio_direct",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E04", "E05"],
                "knowledge_points": ["正比例", "y=kx"],
                "description": "正比例关系应用计算",
                "example_problem": "买3本书花45元，买7本书花多少元？",
                "example_answer": "105元",
                "grade_range": [6],
                "textbook_unit": "六年级下册",
            },
            {
                "id": "ET-0906",
                "name": "反比例应用",
                "code": "ratio_inverse",
                "difficulty_range": ["B", "C"],
                "related_error_codes": ["E04", "E05"],
                "knowledge_points": ["反比例", "xy=k"],
                "description": "反比例关系应用计算",
                "example_problem": "6辆车运货需10趟，10辆车需几趟？",
                "example_answer": "6趟",
                "grade_range": [6],
                "textbook_unit": "六年级下册",
            },
        ],
    },
]


async def seed():
    await init_db()
    async with get_db() as db:
        cursor = await db.execute("SELECT COUNT(*) FROM exercise_types")
        count = (await cursor.fetchone())[0]
        if count > 0:
            print(f"Exercise types already seeded ({count} rows). Skipping.")
            return

        total = 0
        for cat in CATEGORIES:
            await db.execute(
                """INSERT INTO exercise_types
                   (id, parent_id, category, name, code, difficulty_range, related_error_codes,
                    knowledge_points, description, example_problem, example_answer,
                    sort_order, is_active, grade_range, textbook_unit)
                   VALUES (?, NULL, ?, ?, ?, '[]', '[]', '[]', ?, '', '', ?, 1, '[]', '')""",
                (
                    cat["id"], cat["name"], cat["code"], cat["name"],
                    cat["description"], cat["sort_order"],
                ),
            )
            total += 1

            for i, st in enumerate(cat["subtypes"], 1):
                await db.execute(
                    """INSERT INTO exercise_types
                       (id, parent_id, category, name, code, difficulty_range, related_error_codes,
                        knowledge_points, description, example_problem, example_answer,
                        sort_order, is_active, grade_range, textbook_unit)
                       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?)""",
                    (
                        st["id"],
                        cat["id"],
                        cat["name"],
                        st["name"],
                        st["code"],
                        json.dumps(st.get("difficulty_range", ["A", "B", "C"]), ensure_ascii=False),
                        json.dumps(st.get("related_error_codes", []), ensure_ascii=False),
                        json.dumps(st.get("knowledge_points", []), ensure_ascii=False),
                        st.get("description", ""),
                        st.get("example_problem", ""),
                        st.get("example_answer", ""),
                        i,
                        json.dumps(st.get("grade_range", [5, 6]), ensure_ascii=False),
                        st.get("textbook_unit", ""),
                    ),
                )
                total += 1

        await db.commit()
        print(f"Seeded {total} exercise types ({len(CATEGORIES)} categories + subtypes).")


if __name__ == "__main__":
    asyncio.run(seed())
